include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-weijin
PKG_VERSION:=14.3
PKG_RELEASE:=1

LUCI_TITLE:=Weijin Net (惟谨智网)
LUCI_PKGARCH:=all
LUCI_DEPENDS:=+luci-compat +curl +tailscale

PKG_MAINTAINER:=tuina120 <tuina@ianqiao.com>
PKG_LICENSE:=MIT

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt build system magic
